# Generated by Django 4.2.7 on 2023-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(default=None, max_length=5000, null=True, upload_to='index_banner/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(default=None, max_length=5000, null=True, upload_to='news/'),
        ),
    ]
