# Generated by Django 4.2.7 on 2023-12-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_indexbanner_alter_service_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.FileField(default=None, max_length=5000, null=True, upload_to='index_banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
    ]
