# Generated by Django 4.2.7 on 2023-12-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_logo_remove_service_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
