# Generated by Django 4.2.7 on 2023-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maplocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_location', models.TextField()),
            ],
        ),
    ]
