# Generated by Django 4.2.7 on 2023-12-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
