# Generated by Django 4.2.7 on 2023-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('copyright', models.TextField()),
            ],
        ),
    ]
