# Generated by Django 4.2.7 on 2023-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_delete_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('navbar', models.TextField()),
            ],
        ),
    ]
