# Generated by Django 4.2.7 on 2023-12-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
