# Generated by Django 4.2.7 on 2023-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_delete_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.TextField()),
                ('navbar_link', models.TextField()),
                ('navbar_content', models.TextField()),
                ('navbar_icon', models.TextField()),
            ],
        ),
    ]
