# Generated by Django 4.2.7 on 2023-12-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='header_title',
        ),
    ]
