# Generated by Django 4.2.7 on 2023-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_header_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='navbar_icon',
            field=models.FileField(default=None, max_length=5000, null=True, upload_to='index_banner/'),
        ),
    ]
