# Generated by Django 4.2.7 on 2023-12-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_header_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header_Title',
        ),
    ]
