# Generated by Django 4.2.7 on 2023-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_delete_header_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.TextField()),
                ('product_desc', models.TextField()),
                ('product_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
            ],
        ),
    ]
