# Generated by Django 4.2.7 on 2023-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whywe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_title', models.TextField()),
                ('why_desc', models.TextField()),
            ],
        ),
    ]
