# Generated by Django 4.2.7 on 2023-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_whywe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitingcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
                ('back_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
            ],
        ),
    ]
