# Generated by Django 4.2.7 on 2023-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_visitingcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='back_img',
            field=models.FileField(default=None, max_length=5000, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='front_img',
            field=models.FileField(default=None, max_length=5000, null=True, upload_to='img/'),
        ),
    ]
