# Generated by Django 4.2.7 on 2023-12-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_visitingcard_back_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_desc',
            new_name='index_product_desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_img',
            new_name='index_product_img',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_title',
            new_name='index_product_title',
        ),
    ]
