# Generated by Django 4.2.7 on 2023-12-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_rename_product_desc_products_index_product_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='IndexProducts',
        ),
    ]
