# Generated by Django 4.2.7 on 2023-12-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexproducts',
            name='index_external_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='external_link',
            field=models.TextField(null=True),
        ),
    ]
