# Generated by Django 4.2.7 on 2023-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_indexproducts_index_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexproducts',
            name='index_external_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='external_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
