# Generated by Django 4.2.7 on 2023-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_productsarchitecture_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_product_title', models.TextField()),
                ('design_product_desc', models.TextField()),
                ('design_external_link', models.TextField(blank=True, null=True)),
                ('design_product_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_product_title', models.TextField()),
                ('game_product_desc', models.TextField()),
                ('game_external_link', models.TextField(blank=True, null=True)),
                ('game_product_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
            ],
        ),
    ]
