# Generated by Django 4.2.7 on 2023-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_productsdesign_productsgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_title', models.TextField()),
                ('product_category_desc', models.TextField()),
                ('product_category_img', models.FileField(default=None, max_length=5000, null=True, upload_to='productimg/')),
            ],
        ),
    ]
