# Generated by Django 4.2.7 on 2023-12-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_servicescategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicescategory',
            old_name='product_category_desc',
            new_name='services_category_desc',
        ),
        migrations.RenameField(
            model_name='servicescategory',
            old_name='product_category_img',
            new_name='services_category_img',
        ),
        migrations.RenameField(
            model_name='servicescategory',
            old_name='product_category_title',
            new_name='services_category_title',
        ),
    ]
