# Generated by Django 4.2.7 on 2023-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_rename_product_category_desc_servicescategory_services_category_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexproducts',
            name='index_product_desc',
        ),
    ]
